spring.application.name=e-commerce

spring.datasource.url=${URL}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.session.timeout=86400
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz1234567890
jwt.expiration=86400000